#!/usr/bin/env python3
"""Generate sitemap XML from public index.html pages."""

from __future__ import annotations

import argparse
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom import minidom


EXCLUDE_PATH_PARTS = {
    ".git",
    ".github",
    ".vscode",
    "node_modules",
    "private-use",
}

EXCLUDE_DIR_PREFIXES = {
    "news/test",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate sitemap.xml from index.html files")
    parser.add_argument("--root", default=".", help="Project root directory")
    parser.add_argument("--base-url", default="https://www.gasgx.com", help="Site base URL")
    parser.add_argument("--output", default="sitemap.html", help="Output sitemap file path")
    return parser.parse_args()


def should_exclude(relative_path: str) -> bool:
    normalized = relative_path.replace("\\", "/")
    parts = [part for part in normalized.split("/") if part and part != "."]
    if any(part in EXCLUDE_PATH_PARTS for part in parts):
        return True
    return any(normalized == prefix or normalized.startswith(f"{prefix}/") for prefix in EXCLUDE_DIR_PREFIXES)


def route_from_index(index_file: Path, root: Path) -> str:
    rel = index_file.relative_to(root).as_posix()
    if rel == "index.html":
        return "/"
    route = "/" + rel.removesuffix("/index.html")
    return route.rstrip("/") or "/"


def infer_changefreq_priority(route: str) -> tuple[str, str]:
    if route == "/":
        return "daily", "1.0"
    if route.startswith("/news"):
        if route == "/news":
            return "daily", "0.9"
        return "daily", "0.8"

    depth = route.count("/")
    if depth <= 1:
        return "weekly", "0.8"
    return "weekly", "0.7"


def iter_index_files(root: Path) -> Iterable[Path]:
    for index_file in sorted(root.rglob("index.html")):
        rel_parent = index_file.parent.relative_to(root).as_posix()
        if rel_parent == ".":
            rel_parent = ""
        if should_exclude(rel_parent):
            continue
        yield index_file


def resolve_lastmod(index_file: Path, root: Path) -> str:
    rel = index_file.relative_to(root).as_posix()
    git_date = ""

    try:
        result = subprocess.run(
            ["git", "-C", str(root), "log", "-1", "--format=%cs", "--", rel],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            git_date = result.stdout.strip()
    except OSError:
        git_date = ""

    if git_date:
        return git_date

    mtime = datetime.fromtimestamp(index_file.stat().st_mtime, tz=timezone.utc)
    return mtime.strftime("%Y-%m-%d")


def build_sitemap(root: Path, base_url: str) -> Element:
    base = base_url.rstrip("/")
    urlset = Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")

    route_to_file: dict[str, Path] = {}
    for index_file in iter_index_files(root):
        route = route_from_index(index_file, root)
        route_to_file.setdefault(route, index_file)

    ordered_routes = sorted(route_to_file.keys(), key=lambda item: (item != "/", item))
    for route in ordered_routes:
        index_file = route_to_file[route]

        url = SubElement(urlset, "url")
        loc = SubElement(url, "loc")
        loc.text = f"{base}{route}" if route != "/" else f"{base}/"

        lastmod = SubElement(url, "lastmod")
        lastmod.text = resolve_lastmod(index_file, root)

        changefreq, priority = infer_changefreq_priority(route)
        SubElement(url, "changefreq").text = changefreq
        SubElement(url, "priority").text = priority

    return urlset


def write_xml(urlset: Element, output_path: Path) -> None:
    raw = tostring(urlset, encoding="utf-8")
    pretty = minidom.parseString(raw).toprettyxml(indent="  ", encoding="UTF-8")

    lines = pretty.decode("utf-8").splitlines()
    cleaned = [line for line in lines if line.strip()]

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    if cleaned and cleaned[0].startswith("<?xml"):
        cleaned.insert(1, f"<!-- Auto-generated by scripts/generate_sitemap.py at {generated_at} -->")

    output_path.write_text("\n".join(cleaned) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    root = Path(args.root).resolve()
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = root / output_path

    urlset = build_sitemap(root, args.base_url)
    write_xml(urlset, output_path)


if __name__ == "__main__":
    main()
