window.GASGX_QUOTE_PAGES = {
  vman: {
    company: { brandShort: 'VMAN', brandFull: 'VMAN Engineering', supplierName: 'VMAN Engineering', senderEmail: 'allen@vman-engine.com', subjectName: 'VMAN Engineering' },
    title: { zh: 'VMAN Engineering 产品报价总览', en: 'VMAN Engineering Product Quotation Overview', ru: 'Обзор продукции и цен VMAN Engineering' },
    footerText: {
      zh: '<span class="text-[var(--gas-green-light)] font-bold">///</span> 本报价基于全球实时汇率智能生成。最终价格以双方签订的正式商业合同为准。VMAN Engineering 保留最终解释权。',
      en: '<span class="text-[var(--gas-green-light)] font-bold">///</span> This quotation is generated based on real-time exchange rates. Final prices are subject to the official commercial contract. VMAN Engineering reserves the right of final interpretation.',
      ru: '<span class="text-[var(--gas-green-light)] font-bold">///</span> Данное предложение создано на основе курсов валют в реальном времени. Окончательные цены определяются официальным коммерческим контрактом. VMAN Engineering.'
    },
    rates: { USD: 0.1398, EUR: 0.1265, CAD: 0.1888, RUB: 12.866 },
    totalMode: 'legacy-line-items',
    share: { adminEmails: ['cuitengwei@gasgx.com'], signingSecret: 'GasGx::VMAN::ShareGate::20260321', unlockPrefix: 'vman-share-unlocked' },
    productMappings: [
      { id: 'p1200gf', titlePath: 'part2.desc', itemsPath: 'part2.items1' },
      { id: 'p2000gf', titlePath: 'part2.desc2', itemsPath: 'part2.items2' }
    ],
    rawData: {
        part1: {
            desc: { zh: "HTM+ 500kW Gas Genset & Miner Rack Module", en: "HTM+ 500kW Gas Genset & Miner Rack Module", ru: "HTM+ 500kW Gas Genset & Miner Rack Module" },
            items1: [
                { id:"01", brand:"HTM+", qty:"1", price:607200, n:{ zh:"HTM+ Gas Engine 250kW*2 Set", en:"HTM+ Gas Engine 250kW*2 Set", ru:"HTM+ Gas Engine 250kW*2 Set" } },
                { id:"02", brand:"EvoTec", qty:"1", price:47026, n:{ zh:"EvoTec Alternator", en:"EvoTec Alternator", ru:"EvoTec Alternator" } },
                { id:"03", brand:"Woodward", qty:"1", price:66000, n:{ zh:"Woodward Control System", en:"Woodward Control System", ru:"Woodward Control System" } },
                { id:"04", brand:"-", qty:"1", price:-1, n:{ zh:"Smart Breaker", en:"Smart Breaker", ru:"Smart Breaker" } },
                { id:"05", brand:"-", qty:"1", price:-1, n:{ zh:"Exhaust Explosion-proof Valve", en:"Exhaust Explosion-proof Valve", ru:"Exhaust Explosion-proof Valve" } },
                { id:"06", brand:"Dungs", qty:"1", price:-1, n:{ zh:"Gas Supply Valve Dungs", en:"Gas Supply Valve Dungs", ru:"Gas Supply Valve Dungs" } },
                { id:"07", brand:"-", qty:"1", price:-1, n:{ zh:"Jacket Water Heater", en:"Jacket Water Heater", ru:"Jacket Water Heater" } },
                { id:"08", brand:"-", qty:"1", price:-1, n:{ zh:"Alternator Water Tank", en:"Alternator Water Tank", ru:"Alternator Water Tank" } },
                { id:"09", brand:"-", qty:"1", price:-1, n:{ zh:"Alternator Cooling Skid", en:"Alternator Cooling Skid", ru:"Alternator Cooling Skid" } },
                { id:"10", brand:"-", qty:"1", price:-1, n:{ zh:"Mounting Frame & Materials", en:"Mounting Frame & Materials", ru:"Mounting Frame & Materials" } },
                { id:"11", brand:"-", qty:"1", price:361200, n:{ zh:"Liquid Cooling Miner Module", en:"Liquid Cooling Miner Module", ru:"Liquid Cooling Miner Module" } },
                { id:"12", brand:"-", qty:"1", price:127200, n:{ zh:"40HQ Special Container", en:"40HQ Special Container", ru:"40HQ Special Container" } },
                { id:"13", brand:"-", qty:"1", price:6000, n:{ zh:"Integration Transfer Fee", en:"Integration Transfer Fee", ru:"Integration Transfer Fee" } },
                { id:"14", brand:"-", qty:"1", price:30000, n:{ zh:"Installation & Testing Fee", en:"Installation & Testing Fee", ru:"Installation & Testing Fee" } }
            ],
            desc2: { zh: "DT30+ 550kW Gas Genset & Miner Rack Module", en: "DT30+ 550kW Gas Genset & Miner Rack Module", ru: "DT30+ 550kW Gas Genset & Miner Rack Module" },
            items2: [
                { id:"01", brand:"Vman", qty:"1", price:418646, n:{ zh:"DT30+ Gas Engine 550kW", en:"DT30+ Gas Engine 550kW", ru:"DT30+ Gas Engine 550kW" } },
                { id:"02", brand:"Leroy-Somer", qty:"1", price:95026, n:{ zh:"Leroy-Somer LSA49.3 Alternator", en:"Leroy-Somer LSA49.3 Alternator", ru:"Leroy-Somer LSA49.3 Alternator" } },
                { id:"03", brand:"Leroy-Somer", qty:"1", price:3919, n:{ zh:"AVR Upgrade to D350", en:"AVR Upgrade to D350", ru:"AVR Upgrade to D350" } },
                { id:"04", brand:"-", qty:"1", price:133560, n:{ zh:"Control System", en:"Control System", ru:"Control System" } },
                { id:"05", brand:"ABB", qty:"1", price:16800, n:{ zh:"ABB Smart Breaker", en:"ABB Smart Breaker", ru:"ABB Smart Breaker" } },
                { id:"06", brand:"-", qty:"1", price:936, n:{ zh:"ATS Switch", en:"ATS Switch", ru:"ATS Switch" } },
                { id:"07", brand:"-", qty:"1", price:12360, n:{ zh:"Exhaust Valve & Effector", en:"Exhaust Valve & Effector", ru:"Exhaust Valve & Effector" } },
                { id:"08", brand:"Dungs", qty:"1", price:38390, n:{ zh:"Gas Supply Valve Dungs", en:"Gas Supply Valve Dungs", ru:"Gas Supply Valve Dungs" } },
                { id:"09", brand:"-", qty:"1", price:5400, n:{ zh:"Jacket Water Heater", en:"Jacket Water Heater", ru:"Jacket Water Heater" } },
                { id:"10", brand:"-", qty:"1", price:54000, n:{ zh:"Water Tank", en:"Water Tank", ru:"Water Tank" } },
                { id:"11", brand:"-", qty:"1", price:37114, n:{ zh:"Cooling Skid", en:"Cooling Skid", ru:"Cooling Skid" } },
                { id:"12", brand:"-", qty:"1", price:39510, n:{ zh:"Mounting Frame & Materials", en:"Mounting Frame & Materials", ru:"Mounting Frame & Materials" } },
                { id:"13", brand:"-", qty:"1", price:361200, n:{ zh:"Liquid Cooling Miner Module", en:"Liquid Cooling Miner Module", ru:"Liquid Cooling Miner Module" } },
                { id:"14", brand:"-", qty:"1", price:151200, n:{ zh:"40HQ Special Container", en:"40HQ Special Container", ru:"40HQ Special Container" } },
                { id:"15", brand:"-", qty:"1", price:6000, n:{ zh:"Integration Transfer Fee", en:"Integration Transfer Fee", ru:"Integration Transfer Fee" } },
                { id:"16", brand:"-", qty:"1", price:36000, n:{ zh:"Installation Fee", en:"Installation Fee", ru:"Installation Fee" } }
            ]
        },
        part2: {
            desc: { zh: "P1200GF（1200kW | 400V/50HZ）独立燃气发电系统", en: "P1200GF (1200kW | 400V/50HZ)", ru: "P1200GF (1200 кВт | 400В/50Гц) автономная газовая электростанция" },
            items1: [
                { id:"-", brand:"-", qty:"-", price:1476200, isHeader:true, n:{ zh:"基础发电机组", en:"Basic GenSet", ru:"Базовый генераторный агрегат" } },
                { id:"I-1", brand:"Vman", qty:"1", price:-1, n:{ zh:"VMAN DT58 燃气发动机", en:"VMAN DT58 Gas Engine", ru:"Газовый двигатель VMAN DT58" } },
                { id:"I-2", brand:"Vman", qty:"1", price:-1, n:{ zh:"HEINZMANN 控制系统", en:"HEINZMANN control system", ru:"Система управления HEINZMANN" } },
                { id:"I-3", brand:"ABB", qty:"1", price:-1, n:{ zh:"ABB 涡轮增压器", en:"ABB Turbocharger", ru:"Турбокомпрессор ABB" } },
                { id:"I-4", brand:"Vman", qty:"1", price:-1, n:{ zh:"安装底架", en:"Mounting frame", ru:"Монтажная рама" } },
                { id:"I-5", brand:"VULKAN", qty:"1", price:-1, n:{ zh:"弹性联轴器", en:"Elastic coupling", ru:"Эластичная муфта" } },
                { id:"I-6", brand:"Leroy-Somer", qty:"1", price:-1, n:{ zh:"400V 发电机 LSA50.2 L8", en:"400V Alternator LSA50.2 L8", ru:"Альтернатор 400В LSA50.2 L8" } },
                { id:"-", brand:"-", qty:"-", price:1131100, isHeader:true, n:{ zh:"系统配置", en:"System Options", ru:"Системные опции" } },
                { id:"II-1", brand:"Galanz/Wilo/Siemens", qty:"1", price:224000, n:{ zh:"冷却系统", en:"Cooling system", ru:"Система охлаждения" } },
                { id:"II-2", brand:"V-Corelink 1200", qty:"1", price:135000, n:{ zh:"机组控制系统", en:"Genset control system", ru:"Система управления генератором" } },
                { id:"II-3a", brand:"Schneider", qty:"1", price:100000, n:{ zh:"高压开关柜", en:"High Voltage Switch Cabinet", ru:"Высоковольтный шкаф" } },
                { id:"II-3b", brand:"ABB", qty:"1", price:0, n:{ zh:"低压开关柜", en:"Low Voltage Switch Cabinet", ru:"Низковольтный шкаф" } },
                { id:"II-4a", brand:"Vman DN250", qty:"1", price:20000, n:{ zh:"排气系统-消音器", en:"Exhaust System - Muffler", ru:"Выхлопная система - глушитель" } },
                { id:"II-4b", brand:"Vman", qty:"1", price:4800, n:{ zh:"排气防爆阀", en:"Exhaust explosion-proof valve", ru:"Взрывозащищенный клапан выхлопа" } },
                { id:"II-5a", brand:"Dungs", qty:"1", price:11300, n:{ zh:"燃气阀-过滤器", en:"Gas valve - Filter", ru:"Газовый клапан - фильтр" } },
                { id:"II-5b", brand:"Dungs", qty:"1", price:19000, n:{ zh:"燃气阀-电磁阀", en:"Gas valve - Solenoid valve", ru:"Газовый клапан - электромагнитный клапан" } },
                { id:"II-5c", brand:"Dungs", qty:"1", price:9000, n:{ zh:"燃气阀-调压器", en:"Gas valve - Pressure regulator", ru:"Газовый клапан - регулятор давления" } },
                { id:"II-6", brand:"Vman", qty:"1", price:10000, n:{ zh:"专用工具", en:"Special tools", ru:"Специальные инструменты" } },
                { id:"II-7", brand:"Smartgen", qty:"1", price:34000, n:{ zh:"电加热水预热器", en:"Electric Water Preheater", ru:"Электрический предпусковой подогреватель воды" } },
                { id:"II-8", brand:"Vman", qty:"1", price:7600, n:{ zh:"蓄电池（DC24V，4*195Ah）", en:"Battery (DC24V, 4*195Ah)", ru:"Аккумулятор (DC24V, 4*195Ah)" } },
                { id:"II-9a", brand:"Set", qty:"1", price:118500, n:{ zh:"余热回收-热水锅炉", en:"Heat recovery - Hot water boiler", ru:"Утилизация тепла - водогрейный котел" } },
                { id:"II-9b", brand:"Set", qty:"1", price:127500, n:{ zh:"余热回收-蒸汽锅炉", en:"Heat recovery - Steam boiler", ru:"Утилизация тепла - паровой котел" } },
                { id:"II-10", brand:"VULKAN", qty:"8", price:10400, n:{ zh:"弹簧减震器 3200kg", en:"Spring shock absorber 3200kg", ru:"Пружинный амортизатор 3200 кг" } },
                { id:"II-11", brand:"Vman", qty:"1", price:300000, n:{ zh:"40HQ 集装箱", en:"Container 40HQ", ru:"Контейнер 40HQ" } }
            ],
            desc2: { zh: "P2000GF（2000kW | 400V/50HZ）独立燃气发电系统", en: "P2000GF (2000kW | 400V/50HZ)", ru: "P2000GF (2000 кВт | 400В/50Гц) автономная газовая электростанция" },
            items2: [
                { id:"-", brand:"-", qty:"-", price:3290000, isHeader:true, n:{ zh:"基础发电机组", en:"Basic GenSet", ru:"Базовый генераторный агрегат" } },
                { id:"I-1", brand:"Vman", qty:"1", price:-1, n:{ zh:"HND CHG622V20 燃气发动机", en:"HND CHG622V20 Gas Engine", ru:"Газовый двигатель HND CHG622V20" } },
                { id:"I-2", brand:"Vman", qty:"1", price:-1, n:{ zh:"Heinzmann 控制系统柜", en:"Heinzmann control system cabinet", ru:"Шкаф управления Heinzmann" } },
                { id:"I-3", brand:"ABB", qty:"1", price:-1, n:{ zh:"ABB 涡轮增压器", en:"ABB turbocharger", ru:"Турбокомпрессор ABB" } },
                { id:"I-4", brand:"HND", qty:"1", price:-1, n:{ zh:"安装底架", en:"Mounting frame", ru:"Монтажная рама" } },
                { id:"I-5", brand:"VULKAN", qty:"1", price:-1, n:{ zh:"弹性联轴器", en:"Elastic coupling", ru:"Эластичная муфта" } },
                { id:"I-6", brand:"Leroy-Somer", qty:"1", price:-1, n:{ zh:"400V 发电机 LSA52.3 U16", en:"400V Alternator LSA52.3 U16", ru:"Альтернатор 400В LSA52.3 U16" } },
                { id:"-", brand:"-", qty:"-", price:1630115, isHeader:true, n:{ zh:"系统配置", en:"System Options", ru:"Системные опции" } },
                { id:"II-1", brand:"Galanz/Wilo/Siemens", qty:"1", price:305000, n:{ zh:"冷却系统", en:"Cooling system", ru:"Система охлаждения" } },
                { id:"II-2", brand:"V-Corelink2000", qty:"1", price:135000, n:{ zh:"机组控制系统", en:"Genset control system", ru:"Система управления генератором" } },
                { id:"II-3a", brand:"Schneider", qty:"1", price:100000, n:{ zh:"高压开关柜", en:"High Voltage Switch Cabinet", ru:"Высоковольтный шкаф" } },
                { id:"II-3b", brand:"ABB", qty:"1", price:55000, n:{ zh:"低压开关柜", en:"Low Voltage Switch Cabinet", ru:"Низковольтный шкаф" } },
                { id:"II-4a", brand:"HND DN400", qty:"1", price:23000, n:{ zh:"排气系统-消音器", en:"Exhaust System - Muffler", ru:"Выхлопная система - глушитель" } },
                { id:"II-4b", brand:"HND", qty:"1", price:4800, n:{ zh:"排气防爆阀", en:"Exhaust explosion-proof valve", ru:"Взрывозащищенный клапан выхлопа" } },
                { id:"II-5a", brand:"Dungs", qty:"1", price:13500, n:{ zh:"燃气阀-过滤器", en:"Gas valve - Filter", ru:"Газовый клапан - фильтр" } },
                { id:"II-5b", brand:"Dungs", qty:"1", price:27300, n:{ zh:"燃气阀-电磁阀", en:"Gas valve - Solenoid valve", ru:"Газовый клапан - электромагнитный клапан" } },
                { id:"II-5c", brand:"Dungs", qty:"1", price:15515, n:{ zh:"燃气阀-调压器", en:"Gas valve - Pressure regulator", ru:"Газовый клапан - регулятор давления" } },
                { id:"II-6", brand:"HND", qty:"1", price:10000, n:{ zh:"专用工具", en:"Special tools", ru:"Специальные инструменты" } },
                { id:"II-7", brand:"Smartgen", qty:"1", price:34000, n:{ zh:"电加热水预热器", en:"Electric Water Preheater", ru:"Электрический предпусковой подогреватель воды" } },
                { id:"II-8", brand:"HND", qty:"1", price:11400, n:{ zh:"蓄电池（DC24V，6*195Ah）", en:"Battery (DC24V, 6*195Ah)", ru:"Аккумулятор (DC24V, 6*195Ah)" } },
                { id:"II-9a", brand:"Set", qty:"1", price:225000, n:{ zh:"余热回收-热水锅炉", en:"Heat recovery - Hot water boiler", ru:"Утилизация тепла - водогрейный котел" } },
                { id:"II-9b", brand:"Set", qty:"1", price:255000, n:{ zh:"余热回收-蒸汽锅炉", en:"Heat recovery - Steam boiler", ru:"Утилизация тепла - паровой котел" } },
                { id:"II-10", brand:"VULKAN", qty:"12", price:15600, n:{ zh:"弹簧减震器 3200kg", en:"Spring shock absorber 3200kg", ru:"Пружинный амортизатор 3200 кг" } },
                { id:"II-11", brand:"Vman", qty:"1", price:400000, n:{ zh:"13000X3500X3500mm 集装箱", en:"Container 13000X3500X3500mm", ru:"Контейнер 13000X3500X3500мм" } }
            ]
        }
    }
  },
  minerpower: {
    company: { brandShort: 'MinerPower', brandFull: 'MinerPower', supplierName: 'MinerPower', senderEmail: 'sales@minerpower.com', subjectName: 'MinerPower' },
    title: { zh: 'MinerPower 产品报价总览', en: 'MinerPower Product Quotation Overview', ru: 'Обзор продукции и цен MinerPower' },
    footerText: {
      zh: '<span class="text-[var(--gas-green-light)] font-bold">///</span> 本报价基于全球实时汇率智能生成。最终价格以双方签订的正式商业合同为准。MinerPower 保留最终解释权。',
      en: '<span class="text-[var(--gas-green-light)] font-bold">///</span> This quotation is generated based on real-time exchange rates. Final prices are subject to the official commercial contract. MinerPower reserves the right of final interpretation.',
      ru: '<span class="text-[var(--gas-green-light)] font-bold">///</span> Данное предложение создано на основе курсов валют в реальном времени. Окончательные цены определяются официальным коммерческим контрактом. MinerPower.'
    },
    rates: { USD: 0.1398, EUR: 0.1265, CAD: 0.1888, RUB: 12.866 },
    totalMode: 'legacy-line-items',
    share: { adminEmails: ['cuitengwei@gasgx.com'], signingSecret: 'GasGx::MinerPower::ShareGate::20260321', unlockPrefix: 'minerpower-share-unlocked' },
    productMappings: [
      { id: 'miner-rack-module', titlePath: 'part1.desc', itemsPath: 'part1.items1' }
    ],
    rawData: {
        part1: {
            desc: { zh: "HTM+ 500kW 燃气发电机组及矿机机位模块", en: "HTM+ 500kW Gas Genset & Miner Rack Module", ru: "Газогенератор HTM+ 500 кВт и модуль майнинг-стоек" },
            items1: [
                { id:"01", brand:"HTM+", qty:"1", price:607200, n:{ zh:"HTM+ 燃气发动机 250kW*2 机组", en:"HTM+ Gas Engine 250kW*2 Set", ru:"Газовый двигатель HTM+ 250 кВт*2" } },
                { id:"02", brand:"EvoTec", qty:"1", price:47026, n:{ zh:"EvoTec 发电机", en:"EvoTec Alternator", ru:"Альтернатор EvoTec" } },
                { id:"03", brand:"Woodward", qty:"1", price:66000, n:{ zh:"Woodward 控制系统", en:"Woodward Control System", ru:"Система управления Woodward" } },
                { id:"04", brand:"-", qty:"1", price:-1, n:{ zh:"智能断路器", en:"Smart Breaker", ru:"Интеллектуальный выключатель" } },
                { id:"05", brand:"-", qty:"1", price:-1, n:{ zh:"排气防爆阀", en:"Exhaust Explosion-proof Valve", ru:"Взрывозащищенный клапан выхлопа" } },
                { id:"06", brand:"Dungs", qty:"1", price:-1, n:{ zh:"Dungs 燃气供气阀", en:"Gas Supply Valve Dungs", ru:"Газовый клапан Dungs" } },
                { id:"07", brand:"-", qty:"1", price:-1, n:{ zh:"缸套水加热器", en:"Jacket Water Heater", ru:"Подогреватель рубашки охлаждения" } },
                { id:"08", brand:"-", qty:"1", price:-1, n:{ zh:"发电机水箱", en:"Alternator Water Tank", ru:"Бак охлаждения генератора" } },
                { id:"09", brand:"-", qty:"1", price:-1, n:{ zh:"发电机冷却撬", en:"Alternator Cooling Skid", ru:"Охлаждающий модуль генератора" } },
                { id:"10", brand:"-", qty:"1", price:-1, n:{ zh:"安装底座及辅材", en:"Mounting Frame & Materials", ru:"Рама и монтажные материалы" } },
                { id:"11", brand:"-", qty:"1", price:361200, n:{ zh:"液冷矿机机位模块", en:"Liquid Cooling Miner Module", ru:"Модуль жидкостного охлаждения майнеров" } },
                { id:"12", brand:"-", qty:"1", price:127200, n:{ zh:"40HQ 特种集装箱", en:"40HQ Special Container", ru:"Спецконтейнер 40HQ" } },
                { id:"13", brand:"-", qty:"1", price:6000, n:{ zh:"集成转运费", en:"Integration Transfer Fee", ru:"Транспортировка и интеграция" } },
                { id:"14", brand:"-", qty:"1", price:30000, n:{ zh:"安装调试费", en:"Installation & Testing Fee", ru:"Монтаж и пусконаладка" } }
            ],
            desc2: { zh: "DT30+ 550kW Gas Genset & Miner Rack Module", en: "DT30+ 550kW Gas Genset & Miner Rack Module", ru: "DT30+ 550kW Gas Genset & Miner Rack Module" },
            items2: [
                { id:"01", brand:"MinerPower", qty:"1", price:418646, n:{ zh:"DT30+ Gas Engine 550kW", en:"DT30+ Gas Engine 550kW", ru:"DT30+ Gas Engine 550kW" } },
                { id:"02", brand:"Leroy-Somer", qty:"1", price:95026, n:{ zh:"Leroy-Somer LSA49.3 Alternator", en:"Leroy-Somer LSA49.3 Alternator", ru:"Leroy-Somer LSA49.3 Alternator" } },
                { id:"03", brand:"Leroy-Somer", qty:"1", price:3919, n:{ zh:"AVR Upgrade to D350", en:"AVR Upgrade to D350", ru:"AVR Upgrade to D350" } },
                { id:"04", brand:"-", qty:"1", price:133560, n:{ zh:"Control System", en:"Control System", ru:"Control System" } },
                { id:"05", brand:"ABB", qty:"1", price:16800, n:{ zh:"ABB Smart Breaker", en:"ABB Smart Breaker", ru:"ABB Smart Breaker" } },
                { id:"06", brand:"-", qty:"1", price:936, n:{ zh:"ATS Switch", en:"ATS Switch", ru:"ATS Switch" } },
                { id:"07", brand:"-", qty:"1", price:12360, n:{ zh:"Exhaust Valve & Effector", en:"Exhaust Valve & Effector", ru:"Exhaust Valve & Effector" } },
                { id:"08", brand:"Dungs", qty:"1", price:38390, n:{ zh:"Gas Supply Valve Dungs", en:"Gas Supply Valve Dungs", ru:"Gas Supply Valve Dungs" } },
                { id:"09", brand:"-", qty:"1", price:5400, n:{ zh:"Jacket Water Heater", en:"Jacket Water Heater", ru:"Jacket Water Heater" } },
                { id:"10", brand:"-", qty:"1", price:54000, n:{ zh:"Water Tank", en:"Water Tank", ru:"Water Tank" } },
                { id:"11", brand:"-", qty:"1", price:37114, n:{ zh:"Cooling Skid", en:"Cooling Skid", ru:"Cooling Skid" } },
                { id:"12", brand:"-", qty:"1", price:39510, n:{ zh:"Mounting Frame & Materials", en:"Mounting Frame & Materials", ru:"Mounting Frame & Materials" } },
                { id:"13", brand:"-", qty:"1", price:361200, n:{ zh:"Liquid Cooling Miner Module", en:"Liquid Cooling Miner Module", ru:"Liquid Cooling Miner Module" } },
                { id:"14", brand:"-", qty:"1", price:151200, n:{ zh:"40HQ Special Container", en:"40HQ Special Container", ru:"40HQ Special Container" } },
                { id:"15", brand:"-", qty:"1", price:6000, n:{ zh:"Integration Transfer Fee", en:"Integration Transfer Fee", ru:"Integration Transfer Fee" } },
                { id:"16", brand:"-", qty:"1", price:36000, n:{ zh:"Installation Fee", en:"Installation Fee", ru:"Installation Fee" } }
            ]
        },
        part2: {
            desc: { zh: "P1200GF (1200kW | 400V/50HZ)", en: "P1200GF (1200kW | 400V/50HZ)", ru: "P1200GF (1200kW | 400V/50HZ)" },
            items1: [
                { id:"-", brand:"-", qty:"-", price:1476200, isHeader:true, n:{ zh:"Basic GenSet", en:"Basic GenSet", ru:"Basic GenSet" } },
                { id:"I-1", brand:"MinerPower", qty:"1", price:-1, n:{ zh:"MinerPower DT58 Gas Engine", en:"MinerPower DT58 Gas Engine", ru:"Газовый двигатель MinerPower DT58" } },
                { id:"I-2", brand:"MinerPower", qty:"1", price:-1, n:{ zh:"HEINZMANN control system", en:"HEINZMANN control system", ru:"Система управления HEINZMANN" } },
                { id:"I-3", brand:"ABB", qty:"1", price:-1, n:{ zh:"ABB Turbocharger", en:"ABB Turbocharger", ru:"ABB Turbocharger" } },
                { id:"I-4", brand:"MinerPower", qty:"1", price:-1, n:{ zh:"Mounting frame", en:"Mounting frame", ru:"Монтажная рама" } },
                { id:"I-5", brand:"VULKAN", qty:"1", price:-1, n:{ zh:"Elastic coupling", en:"Elastic coupling", ru:"Elastic coupling" } },
                { id:"I-6", brand:"Leroy-Somer", qty:"1", price:-1, n:{ zh:"400V Alternator LSA50.2 L8", en:"400V Alternator LSA50.2 L8", ru:"400V Alternator LSA50.2 L8" } },
                { id:"-", brand:"-", qty:"-", price:1131100, isHeader:true, n:{ zh:"System Options", en:"System Options", ru:"System Options" } },
                { id:"II-1", brand:"Galanz/Wilo/Siemens", qty:"1", price:224000, n:{ zh:"Cooling system", en:"Cooling system", ru:"Cooling system" } },
                { id:"II-2", brand:"V-Corelink 1200", qty:"1", price:135000, n:{ zh:"Genset control system", en:"Genset control system", ru:"Genset control system" } },
                { id:"II-3a", brand:"Schneider", qty:"1", price:100000, n:{ zh:"High Voltage Switch Cabinet", en:"High Voltage Switch Cabinet", ru:"High Voltage Switch Cabinet" } },
                { id:"II-3b", brand:"ABB", qty:"1", price:0, n:{ zh:"Low Voltage Switch Cabinet", en:"Low Voltage Switch Cabinet", ru:"Low Voltage Switch Cabinet" } },
                { id:"II-4a", brand:"MinerPower DN250", qty:"1", price:20000, n:{ zh:"Exhaust System - Muffler", en:"Exhaust System - Muffler", ru:"Выхлопная система - глушитель" } },
                { id:"II-4b", brand:"MinerPower", qty:"1", price:4800, n:{ zh:"Exhaust explosion-proof valve", en:"Exhaust explosion-proof valve", ru:"Взрывозащищенный клапан выхлопа" } },
                { id:"II-5a", brand:"Dungs", qty:"1", price:11300, n:{ zh:"Gas valve - Filter", en:"Gas valve - Filter", ru:"Gas valve - Filter" } },
                { id:"II-5b", brand:"Dungs", qty:"1", price:19000, n:{ zh:"Gas valve - Solenoid valve", en:"Gas valve - Solenoid valve", ru:"Gas valve - Solenoid valve" } },
                { id:"II-5c", brand:"Dungs", qty:"1", price:9000, n:{ zh:"Gas valve - Pressure regulator", en:"Gas valve - Pressure regulator", ru:"Gas valve - Pressure regulator" } },
                { id:"II-6", brand:"MinerPower", qty:"1", price:10000, n:{ zh:"Special tools", en:"Special tools", ru:"Специальные инструменты" } },
                { id:"II-7", brand:"Smartgen", qty:"1", price:34000, n:{ zh:"Electric Water Preheater", en:"Electric Water Preheater", ru:"Electric Water Preheater" } },
                { id:"II-8", brand:"MinerPower", qty:"1", price:7600, n:{ zh:"Battery (DC24V, 4*195Ah)", en:"Battery (DC24V, 4*195Ah)", ru:"Аккумулятор (DC24V, 4*195Ah)" } },
                { id:"II-9a", brand:"Set", qty:"1", price:118500, n:{ zh:"Heat recovery - Hot water boiler", en:"Heat recovery - Hot water boiler", ru:"Heat recovery - Hot water boiler" } },
                { id:"II-9b", brand:"Set", qty:"1", price:127500, n:{ zh:"Heat recovery - Steam boiler", en:"Heat recovery - Steam boiler", ru:"Heat recovery - Steam boiler" } },
                { id:"II-10", brand:"VULKAN", qty:"8", price:10400, n:{ zh:"Spring shock absorber 3200kg", en:"Spring shock absorber 3200kg", ru:"Spring shock absorber 3200kg" } },
                { id:"II-11", brand:"MinerPower", qty:"1", price:300000, n:{ zh:"Container 40HQ", en:"Container 40HQ", ru:"Контейнер 40HQ" } }
            ],
            desc2: { zh: "P2000GF (2000kW | 400V/50HZ)", en: "P2000GF (2000kW | 400V/50HZ)", ru: "P2000GF (2000kW | 400V/50HZ)" },
            items2: [
                { id:"-", brand:"-", qty:"-", price:3290000, isHeader:true, n:{ zh:"Basic GenSet", en:"Basic GenSet", ru:"Basic GenSet" } },
                { id:"I-1", brand:"MinerPower", qty:"1", price:-1, n:{ zh:"HND CHG622V20 Gas Engine", en:"HND CHG622V20 Gas Engine", ru:"Газовый двигатель HND CHG622V20" } },
                { id:"I-2", brand:"MinerPower", qty:"1", price:-1, n:{ zh:"Heinzmann control system cabinet", en:"Heinzmann control system cabinet", ru:"Шкаф управления Heinzmann" } },
                { id:"I-3", brand:"ABB", qty:"1", price:-1, n:{ zh:"ABB turbocharger", en:"ABB turbocharger", ru:"ABB turbocharger" } },
                { id:"I-4", brand:"HND", qty:"1", price:-1, n:{ zh:"Mounting frame", en:"Mounting frame", ru:"Mounting frame" } },
                { id:"I-5", brand:"VULKAN", qty:"1", price:-1, n:{ zh:"Elastic coupling", en:"Elastic coupling", ru:"Elastic coupling" } },
                { id:"I-6", brand:"Leroy-Somer", qty:"1", price:-1, n:{ zh:"400V Alternator LSA52.3 U16", en:"400V Alternator LSA52.3 U16", ru:"400V Alternator LSA52.3 U16" } },
                { id:"-", brand:"-", qty:"-", price:1630115, isHeader:true, n:{ zh:"System Options", en:"System Options", ru:"System Options" } },
                { id:"II-1", brand:"Galanz/Wilo/Siemens", qty:"1", price:305000, n:{ zh:"Cooling system", en:"Cooling system", ru:"Cooling system" } },
                { id:"II-2", brand:"V-Corelink2000", qty:"1", price:135000, n:{ zh:"Genset control system", en:"Genset control system", ru:"Genset control system" } },
                { id:"II-3a", brand:"Schneider", qty:"1", price:100000, n:{ zh:"High Voltage Switch Cabinet", en:"High Voltage Switch Cabinet", ru:"High Voltage Switch Cabinet" } },
                { id:"II-3b", brand:"ABB", qty:"1", price:55000, n:{ zh:"Low Voltage Switch Cabinet", en:"Low Voltage Switch Cabinet", ru:"Low Voltage Switch Cabinet" } },
                { id:"II-4a", brand:"HND DN400", qty:"1", price:23000, n:{ zh:"Exhaust System - Muffler", en:"Exhaust System - Muffler", ru:"Exhaust System - Muffler" } },
                { id:"II-4b", brand:"HND", qty:"1", price:4800, n:{ zh:"Exhaust explosion-proof valve", en:"Exhaust explosion-proof valve", ru:"Exhaust explosion-proof valve" } },
                { id:"II-5a", brand:"Dungs", qty:"1", price:13500, n:{ zh:"Gas valve - Filter", en:"Gas valve - Filter", ru:"Gas valve - Filter" } },
                { id:"II-5b", brand:"Dungs", qty:"1", price:27300, n:{ zh:"Gas valve - Solenoid valve", en:"Gas valve - Solenoid valve", ru:"Gas valve - Solenoid valve" } },
                { id:"II-5c", brand:"Dungs", qty:"1", price:15515, n:{ zh:"Gas valve - Pressure regulator", en:"Gas valve - Pressure regulator", ru:"Gas valve - Pressure regulator" } },
                { id:"II-6", brand:"HND", qty:"1", price:10000, n:{ zh:"Special tools", en:"Special tools", ru:"Special tools" } },
                { id:"II-7", brand:"Smartgen", qty:"1", price:34000, n:{ zh:"Electric Water Preheater", en:"Electric Water Preheater", ru:"Electric Water Preheater" } },
                { id:"II-8", brand:"HND", qty:"1", price:11400, n:{ zh:"Battery (DC24V, 6*195Ah)", en:"Battery (DC24V, 6*195Ah)", ru:"Battery (DC24V, 6*195Ah)" } },
                { id:"II-9a", brand:"Set", qty:"1", price:225000, n:{ zh:"Heat recovery - Hot water boiler", en:"Heat recovery - Hot water boiler", ru:"Heat recovery - Hot water boiler" } },
                { id:"II-9b", brand:"Set", qty:"1", price:255000, n:{ zh:"Heat recovery - Steam boiler", en:"Heat recovery - Steam boiler", ru:"Heat recovery - Steam boiler" } },
                { id:"II-10", brand:"VULKAN", qty:"12", price:15600, n:{ zh:"Spring shock absorber 3200kg", en:"Spring shock absorber 3200kg", ru:"Spring shock absorber 3200kg" } },
                { id:"II-11", brand:"MinerPower", qty:"1", price:400000, n:{ zh:"Container 13000X3500X3500mm", en:"Container 13000X3500X3500mm", ru:"Контейнер 13000X3500X3500мм" } }
            ]
        }
    }
  }
};