alter table if exists public.knowledge_documents
    drop constraint if exists knowledge_documents_source_type_check;

alter table if exists public.knowledge_documents
    add constraint knowledge_documents_source_type_check
    check (source_type in ('public_page', 'site_function', 'resource_doc', 'internal_sales_kb', 'faq', 'datasheet', 'case_study', 'certification'));

with seed (
    canonical_url,
    title,
    excerpt,
    chunk_text,
    chunk_summary,
    keywords,
    feature_group,
    feature_id,
    link_label,
    recommendation_hint,
    path,
    section_path,
    sort_order,
    token_count
) as (
    values
        ('https://www.gasgx.com/', 'GasGx Home', 'Public homepage for products, solutions, tools and resources.', 'GasGx Home is the public entry for navigating products, solutions, tools, rankings, resources and support paths. It is the right first stop when the visitor needs a broad overview before drilling into a specific workflow.', 'Public homepage for navigating products, solutions, tools and support.', array['home', 'homepage', 'website overview', 'site navigation'], 'site_entry', 'home', 'GasGx Home', 'Start here for the broadest public overview.', '/', 'site/home', 100, 42),
        ('https://www.gasgx.com/news/', 'GasGx News', 'Public news hub for flash, data and market updates.', 'GasGx News is the public media and update hub for flash items, data views and market-facing content. It should be referenced when the user is looking for news-style updates rather than product qualification or quotation workflow.', 'Public news hub for flash, data and market updates.', array['news', 'flash', 'data', 'updates', 'market news'], 'site_entry', 'news', 'GasGx News', 'Use this when the request is about public updates or media content.', '/news/', 'site/news', 110, 40),
        ('https://www.gasgx.com/products/', 'GasGx Products', 'Public product catalog by power range, gas type, cooling and deployment.', 'GasGx Products is the public catalog entry for browsing generator directions by power range, gas type, cooling and deployment format. It is the correct route when the visitor wants equipment direction rather than a scenario-only answer.', 'Public product catalog by power range, gas type, cooling and deployment.', array['products', 'product catalog', 'power range', 'deployment', 'cooling'], 'site_entry', 'products', 'Products', 'Open this when the question is mainly about product direction.', '/products/', 'site/products', 120, 45),
        ('https://www.gasgx.com/solutions/', 'GasGx Solutions', 'Public solution hub for oilfield, mining, industrial and CHP scenarios.', 'GasGx Solutions is the public scenario hub for oilfield, mining, industrial distributed generation and CHP paths. It is the correct site entry when the visitor asks which scenario page to open or wants a public solution overview.', 'Public solution hub for oilfield, mining, industrial and CHP scenarios.', array['solutions', 'solution hub', 'oilfield', 'mining', 'industrial', 'chp'], 'site_entry', 'solutions', 'Solutions', 'Open this when the question is about scenario direction.', '/solutions/', 'site/solutions', 130, 44),
        ('https://www.gasgx.com/resources/', 'GasGx Resources', 'Public resource center for datasheets, reports, FAQ and supporting references.', 'GasGx Resources is the public documentation hub for datasheets, reports, FAQ, case studies, certifications, videos and whitepapers. It should be referenced for documentation-stage questions instead of quotation routing.', 'Public resource center for datasheets, reports, FAQ and supporting references.', array['resources', 'datasheets', 'reports', 'faq', 'case studies', 'whitepapers'], 'site_entry', 'resources', 'Resources', 'Use this for documentation-stage questions.', '/resources/', 'site/resources', 140, 45),
        ('https://www.gasgx.com/support/', 'GasGx Support', 'Public support section for service, tech and network information.', 'GasGx Support is the public support section covering service, technical support and network-facing information. It should be used when the user is asking about service boundaries rather than only product selection.', 'Public support section for service, tech and network information.', array['support', 'service', 'technical support', 'service network'], 'site_entry', 'support', 'Support', 'Open this when the request is mainly support-oriented.', '/support/', 'site/support', 150, 40),
        ('https://www.gasgx.com/rankings/', 'GasGx Rankings', 'Public comparative and ranking-style pages.', 'GasGx Rankings is the public comparative section for ranking-style pages, benchmarking views and market-facing comparisons. It should be used when the user wants comparison-oriented content rather than a direct quotation path.', 'Public comparative and ranking-style pages.', array['rankings', 'comparison', 'benchmark', 'ranking pages'], 'site_entry', 'rankings', 'Rankings', 'Use this for comparison-oriented public pages.', '/rankings/', 'site/rankings', 160, 37),
        ('https://www.gasgx.com/tools/', 'GasGx Tools', 'Public tool hub for screening, calculators, analyzers and comparisons.', 'GasGx Tools is the public tool hub for screening, calculators, analyzers and scenario-comparison utilities. It is the right feature entry when the user asks which public tool to use first or which calculators are available.', 'Public tool hub for screening, calculators, analyzers and comparisons.', array['tools', 'tool hub', 'calculator', 'analyzer', 'screening tool'], 'site_entry', 'tools', 'GasGx Tools', 'Use this when the request is about public tools.', '/tools/', 'site/tools', 170, 44),
        ('https://www.gasgx.com/digitalization/platform/', 'GasGx O&M Platform', 'Public digitalization entry for the O&M platform capability page.', 'The GasGx O&M Platform page acts as the main public digitalization entry for operations visibility, diagnostics and platform capability positioning. It is suitable for public digital-system questions, but not for opening internal admin consoles.', 'Public digitalization entry for the O&M platform capability page.', array['digitalization', 'o&m platform', 'operations platform', 'monitoring'], 'digitalization', 'o_m_platform', 'O&M Platform', 'Use this for public digitalization capability questions.', '/digitalization/platform/', 'digitalization/platform', 180, 43),
        ('https://www.gasgx.com/about/contact/', 'Contact GasGx', 'Public contact entry for project, support and cooperation requests.', 'Contact GasGx is the public contact page for project, support and cooperation requests. It is the right route when the visitor needs a public contact entry rather than an internal operator or admin path.', 'Public contact entry for project, support and cooperation requests.', array['contact', 'contact gasgx', 'email', 'support contact'], 'support', 'contact', 'Contact GasGx', 'Use this when the user needs a public contact path.', '/about/contact/', 'support/contact', 190, 40),
        ('https://www.gasgx.com/quote/requirement.html', 'GasGx Requirement Intake', 'Public structured intake for quotation and project qualification.', 'GasGx Requirement Intake is the public structured intake page for quotation follow-up and project qualification. It captures application, power, gas type, gas quality, country, deployment preference and scope boundary in one place.', 'Public structured intake for quotation and project qualification.', array['requirement intake', 'quote form', 'quotation form', 'project brief', 'requirement form'], 'workflow', 'requirement_intake', 'GasGx Requirement Intake', 'Use this when the user needs the public quotation workflow.', '/quote/requirement.html', 'workflow/requirement-intake', 200, 48),
        ('https://www.gasgx.com/solutions/oilfield/', 'Oilfield Solution', 'Public oilfield gas-to-power solution page.', 'The Oilfield Solution page is the public scenario page for oilfield and associated-gas power positioning. It is the correct public route when the user asks for the oilfield solution page instead of a generic scenario summary.', 'Public oilfield gas-to-power solution page.', array['oilfield solution', 'oilfield page', 'associated gas power'], 'solution', 'oilfield_solution', 'Oilfield Solution', 'Use this when the visitor asks for the oilfield scenario page.', '/solutions/oilfield/', 'solutions/oilfield', 210, 38),
        ('https://www.gasgx.com/solutions/mining/', 'Mining Solution', 'Public mining and data-center power solution page.', 'The Mining Solution page is the public scenario page for gas-to-power mining and data-center-style power positioning. It should be referenced when the user asks for the mining solution page rather than a quotation or tool answer.', 'Public mining and data-center power solution page.', array['mining solution', 'data center power', 'mining page'], 'solution', 'mining_solution', 'Mining Solution', 'Use this when the visitor asks for the mining scenario page.', '/solutions/mining/', 'solutions/mining', 220, 39),
        ('https://www.gasgx.com/solutions/industrial/', 'Industrial Solution', 'Public industrial distributed-generation solution page.', 'The Industrial Solution page is the public scenario page for industrial distributed generation and plant-side power positioning. It is the right route when the question is about industrial scenario navigation.', 'Public industrial distributed-generation solution page.', array['industrial solution', 'industrial page', 'distributed generation'], 'solution', 'industrial_solution', 'Industrial Solution', 'Use this when the visitor asks for the industrial scenario page.', '/solutions/industrial/', 'solutions/industrial', 230, 38),
        ('https://www.gasgx.com/solutions/chp/', 'CHP Solution', 'Public CHP and cogeneration solution page.', 'The CHP Solution page is the public route for CHP and cogeneration positioning. It should be referenced when the visitor explicitly asks for the CHP page or wants the public CHP entry.', 'Public CHP and cogeneration solution page.', array['chp solution', 'cogeneration', 'chp page'], 'solution', 'chp_solution', 'CHP Solution', 'Use this when the visitor asks for the CHP scenario page.', '/solutions/chp/', 'solutions/chp', 240, 35),
        ('https://www.gasgx.com/resources/datasheets/', 'GasGx Datasheets', 'Public datasheet library for equipment-detail references.', 'GasGx Datasheets is the public resource entry for equipment-detail references and parameter-sheet style documents. It is the best public route when the question is specifically about datasheets.', 'Public datasheet library for equipment-detail references.', array['datasheets', 'data sheets', 'parameter sheets', 'equipment details'], 'resource', 'datasheets', 'Datasheets', 'Use this when the visitor asks for datasheets.', '/resources/datasheets/', 'resources/datasheets', 250, 39),
        ('https://www.gasgx.com/resources/reports/', 'GasGx Reports', 'Public reports library for market and scenario context.', 'GasGx Reports is the public resource entry for market context, scenario research and longer-form report reading. It is the right route when the question is about reports rather than short FAQ answers.', 'Public reports library for market and scenario context.', array['reports', 'market reports', 'research reports'], 'resource', 'reports', 'Reports', 'Use this when the visitor asks for reports.', '/resources/reports/', 'resources/reports', 260, 36),
        ('https://www.gasgx.com/resources/faq/', 'GasGx FAQ', 'Public FAQ entry for short operational answers.', 'GasGx FAQ is the public short-answer entry for operational and repeated questions. It should be referenced when the visitor wants a fast FAQ-style answer before opening longer documents.', 'Public FAQ entry for short operational answers.', array['faq', 'frequently asked questions', 'short answers'], 'resource', 'faq', 'FAQ', 'Use this when the visitor asks for FAQ.', '/resources/faq/', 'resources/faq', 270, 33),
        ('https://www.gasgx.com/resources/case-studies/', 'GasGx Case Studies', 'Public case-studies library with reference scenarios.', 'GasGx Case Studies is the public case library for reference scenarios and example-style reading. It is useful when the visitor wants examples rather than only specifications.', 'Public case-studies library with reference scenarios.', array['case studies', 'case study', 'reference scenarios'], 'resource', 'case_studies', 'Case Studies', 'Use this when the visitor asks for public examples.', '/resources/case-studies/', 'resources/case-studies', 280, 34),
        ('https://www.gasgx.com/resources/videos/', 'GasGx Videos', 'Public videos library for visual references.', 'GasGx Videos is the public visual reference entry for visitors who prefer video-based overview instead of document-first reading. It is suitable for visual and media-driven guidance.', 'Public videos library for visual references.', array['videos', 'video library', 'visual overview'], 'resource', 'videos', 'Videos', 'Use this when the visitor asks for video references.', '/resources/videos/', 'resources/videos', 290, 31),
        ('https://www.gasgx.com/resources/certifications/', 'GasGx Certifications', 'Public certifications page for certification references.', 'GasGx Certifications is the public certification-reference page. It is useful for certification references, but it should not be treated as a project-specific compliance approval by itself.', 'Public certifications page for certification references.', array['certifications', 'certification page', 'certificate references'], 'resource', 'certifications', 'Certifications', 'Use this when the visitor asks for certification references.', '/resources/certifications/', 'resources/certifications', 300, 35),
        ('https://www.gasgx.com/resources/whitepapers/', 'GasGx Whitepapers', 'Public whitepapers library for longer-form reading.', 'GasGx Whitepapers is the public long-form reading entry for deeper technical or market background. It is useful when the visitor wants a public whitepaper route.', 'Public whitepapers library for longer-form reading.', array['whitepapers', 'white paper', 'long-form resource'], 'resource', 'whitepapers', 'Whitepapers', 'Use this when the visitor asks for whitepapers.', '/resources/whitepapers/', 'resources/whitepapers', 310, 32),
        ('https://www.gasgx.com/support/service/', 'GasGx Service Support', 'Public service-support page.', 'GasGx Service Support is the public service-oriented support page for after-sales and service-boundary questions. It should be used when the visitor wants service-scope direction rather than only a product page.', 'Public service-support page.', array['service support', 'after-sales service', 'service page'], 'support', 'service_support', 'Service Support', 'Use this when the visitor asks about service support.', '/support/service/', 'support/service', 320, 34),
        ('https://www.gasgx.com/support/network/', 'GasGx Service Network', 'Public service-network page.', 'GasGx Service Network is the public entry for regional support-reach and network-facing service questions. It should be used when the visitor asks about network coverage or support reach.', 'Public service-network page.', array['service network', 'support network', 'regional support'], 'support', 'service_network', 'Service Network', 'Use this when the visitor asks about service-network reach.', '/support/network/', 'support/network', 330, 33),
        ('https://www.gasgx.com/support/tech/', 'GasGx Technical Support', 'Public technical-support page.', 'GasGx Technical Support is the public entry for technical-support scope questions. It is the right route when the visitor asks where technical support information lives on the public site.', 'Public technical-support page.', array['technical support', 'tech support', 'support tech'], 'support', 'technical_support', 'Technical Support', 'Use this when the visitor asks about technical support.', '/support/tech/', 'support/tech', 340, 32),
        ('https://www.gasgx.com/vman/', 'VMAN', 'Public VMAN brand entry.', 'VMAN is a public GasGx brand-facing route that can act as a public quote or brand entry. It should be referenced when the visitor explicitly asks for the VMAN page.', 'Public VMAN brand entry.', array['vman', 'vman page', 'brand entry'], 'brand', 'vman', 'VMAN', 'Use this when the visitor asks for the public VMAN route.', '/vman/', 'brand/vman', 350, 30),
        ('https://www.gasgx.com/minerpower/', 'MinerPower', 'Public MinerPower brand entry.', 'MinerPower is a public GasGx brand-facing route for the MinerPower page. It should be referenced when the visitor explicitly asks for the public MinerPower route.', 'Public MinerPower brand entry.', array['minerpower', 'miner power', 'minerpower page'], 'brand', 'minerpower', 'MinerPower', 'Use this when the visitor asks for the public MinerPower route.', '/minerpower/', 'brand/minerpower', 360, 30),
        ('https://www.gasgx.com/tools/site-fit/', 'Site Fit Tool', 'Public feasibility-screening tool for overall project fit.', 'The Site Fit Tool is the first public screening tool for overall project feasibility before quotation. It is the best public route when the visitor asks which tool to use first for feasibility screening.', 'Public feasibility-screening tool for overall project fit.', array['site fit', 'site-fit', 'feasibility screening', 'project fit'], 'tool', 'site_fit', 'Site Fit Tool', 'Use this as the first public screening tool.', '/tools/site-fit/', 'tools/site-fit', 370, 39),
        ('https://www.gasgx.com/tools/gas-fit/', 'Gas Fit Tool', 'Public tool for checking fuel and gas-boundary fit.', 'The Gas Fit Tool is the public route for checking whether the gas source and fuel boundary look workable for a GasGx solution. It should be referenced when the visitor asks about gas-fit screening.', 'Public tool for checking fuel and gas-boundary fit.', array['gas fit', 'gas-fit', 'fuel fit', 'gas boundary'], 'tool', 'gas_fit', 'Gas Fit Tool', 'Use this for fuel-boundary screening.', '/tools/gas-fit/', 'tools/gas-fit', 380, 38),
        ('https://www.gasgx.com/tools/engine-selection/', 'Engine Selection Tool', 'Public tool for narrowing equipment direction.', 'The Engine Selection Tool is the public route for narrowing equipment direction before formal quotation. It should be used when the visitor asks about generator or engine direction as a public tool.', 'Public tool for narrowing equipment direction.', array['engine selection', 'engine-selection', 'generator selection'], 'tool', 'engine_selection', 'Engine Selection Tool', 'Use this to narrow equipment direction before quotation.', '/tools/engine-selection/', 'tools/engine-selection', 390, 38),
        ('https://www.gasgx.com/tools/miner-buying-guide/', 'Miner Buying Guide', 'Public tool for miner procurement direction.', 'Miner Buying Guide is the public route for comparing miner procurement direction against the planned power strategy. It is useful when the visitor asks for a miner-buying guide rather than a quotation workflow.', 'Public tool for miner procurement direction.', array['miner buying guide', 'buying guide', 'miner guide'], 'tool', 'miner_buying_guide', 'Miner Buying Guide', 'Use this when the request is miner-procurement oriented.', '/tools/miner-buying-guide/', 'tools/miner-buying-guide', 400, 34),
        ('https://www.gasgx.com/tools/roi/', 'ROI Calculator', 'Public ROI calculator entry.', 'The ROI Calculator is the public route for estimating return-on-investment direction. It is useful for directional analysis, but should not be treated as a final project commitment.', 'Public ROI calculator entry.', array['roi', 'roi calculator', 'return on investment'], 'tool', 'roi_calculator', 'ROI Calculator', 'Use this for directional ROI analysis.', '/tools/roi/', 'tools/roi', 410, 33),
        ('https://www.gasgx.com/tools/lcoe-calculator/', 'LCOE Calculator', 'Public LCOE calculator entry.', 'The LCOE Calculator is the public route for estimating levelized electricity-cost direction. It is useful when the visitor asks for cost-direction analysis rather than final quotation.', 'Public LCOE calculator entry.', array['lcoe', 'lcoe calculator', 'levelized cost of electricity'], 'tool', 'lcoe_calculator', 'LCOE Calculator', 'Use this for directional electricity-cost analysis.', '/tools/lcoe-calculator/', 'tools/lcoe-calculator', 420, 35),
        ('https://www.gasgx.com/tools/gas-analyzer/', 'Gas Analyzer', 'Public gas-analysis tool entry.', 'Gas Analyzer is the public route for gas-composition and gas-analysis style questions. It is useful when the visitor asks for a gas analyzer rather than a broader quotation route.', 'Public gas-analysis tool entry.', array['gas analyzer', 'gas analyser', 'gas analysis'], 'tool', 'gas_analyzer', 'Gas Analyzer', 'Use this for gas-analysis questions.', '/tools/gas-analyzer/', 'tools/gas-analyzer', 430, 31),
        ('https://www.gasgx.com/tools/global-logistics/', 'Global Logistics', 'Public logistics-analysis tool entry.', 'Global Logistics is the public route for transport, routing and delivery-boundary analysis. It should be referenced when the visitor asks about logistics constraints as a public site feature.', 'Public logistics-analysis tool entry.', array['global logistics', 'logistics', 'shipping constraints'], 'tool', 'global_logistics', 'Global Logistics', 'Use this for logistics-boundary analysis.', '/tools/global-logistics/', 'tools/global-logistics', 440, 33),
        ('https://www.gasgx.com/tools/global-compliance/', 'Global Compliance', 'Public compliance-analysis tool entry.', 'Global Compliance is the public route for high-level compliance and market-entry analysis. It should be referenced when the visitor asks whether GasGx has a public compliance-oriented tool.', 'Public compliance-analysis tool entry.', array['global compliance', 'compliance', 'regulatory'], 'tool', 'global_compliance', 'Global Compliance', 'Use this for high-level compliance analysis.', '/tools/global-compliance/', 'tools/global-compliance', 450, 33)
),
upsert_docs as (
    insert into public.knowledge_documents (
        source_type,
        visibility,
        language,
        title,
        canonical_url,
        excerpt,
        content_markdown,
        source_meta,
        status,
        last_crawled_at
    )
    select
        'site_function',
        'public',
        'en',
        seed.title,
        seed.canonical_url,
        seed.excerpt,
        '# ' || seed.title || E'\n\n' || seed.chunk_text,
        jsonb_build_object(
            'seed', 'public_site_feature_directory_v1',
            'kind', 'site_function',
            'feature_group', seed.feature_group,
            'feature_id', seed.feature_id,
            'path', seed.path,
            'link_label', seed.link_label,
            'recommendation_hint', seed.recommendation_hint
        ),
        'published',
        timezone('utc', now())
    from seed
    on conflict (canonical_url) do update
    set
        source_meta = coalesce(public.knowledge_documents.source_meta, '{}'::jsonb) || excluded.source_meta,
        last_crawled_at = timezone('utc', now()),
        updated_at = timezone('utc', now())
    returning canonical_url
)
select count(*) from upsert_docs;

delete from public.knowledge_chunks
where source_meta ->> 'seed' = 'public_site_feature_directory_v1';

with seed (
    canonical_url,
    title,
    excerpt,
    chunk_text,
    chunk_summary,
    keywords,
    feature_group,
    feature_id,
    link_label,
    recommendation_hint,
    path,
    section_path,
    sort_order,
    token_count
) as (
    values
        ('https://www.gasgx.com/', 'GasGx Home', 'Public homepage for products, solutions, tools and resources.', 'GasGx Home is the public entry for navigating products, solutions, tools, rankings, resources and support paths. It is the right first stop when the visitor needs a broad overview before drilling into a specific workflow.', 'Public homepage for navigating products, solutions, tools and support.', array['home', 'homepage', 'website overview', 'site navigation'], 'site_entry', 'home', 'GasGx Home', 'Start here for the broadest public overview.', '/', 'site/home', 100, 42),
        ('https://www.gasgx.com/news/', 'GasGx News', 'Public news hub for flash, data and market updates.', 'GasGx News is the public media and update hub for flash items, data views and market-facing content. It should be referenced when the user is looking for news-style updates rather than product qualification or quotation workflow.', 'Public news hub for flash, data and market updates.', array['news', 'flash', 'data', 'updates', 'market news'], 'site_entry', 'news', 'GasGx News', 'Use this when the request is about public updates or media content.', '/news/', 'site/news', 110, 40),
        ('https://www.gasgx.com/products/', 'GasGx Products', 'Public product catalog by power range, gas type, cooling and deployment.', 'GasGx Products is the public catalog entry for browsing generator directions by power range, gas type, cooling and deployment format. It is the correct route when the visitor wants equipment direction rather than a scenario-only answer.', 'Public product catalog by power range, gas type, cooling and deployment.', array['products', 'product catalog', 'power range', 'deployment', 'cooling'], 'site_entry', 'products', 'Products', 'Open this when the question is mainly about product direction.', '/products/', 'site/products', 120, 45),
        ('https://www.gasgx.com/solutions/', 'GasGx Solutions', 'Public solution hub for oilfield, mining, industrial and CHP scenarios.', 'GasGx Solutions is the public scenario hub for oilfield, mining, industrial distributed generation and CHP paths. It is the correct site entry when the visitor asks which scenario page to open or wants a public solution overview.', 'Public solution hub for oilfield, mining, industrial and CHP scenarios.', array['solutions', 'solution hub', 'oilfield', 'mining', 'industrial', 'chp'], 'site_entry', 'solutions', 'Solutions', 'Open this when the question is about scenario direction.', '/solutions/', 'site/solutions', 130, 44),
        ('https://www.gasgx.com/resources/', 'GasGx Resources', 'Public resource center for datasheets, reports, FAQ and supporting references.', 'GasGx Resources is the public documentation hub for datasheets, reports, FAQ, case studies, certifications, videos and whitepapers. It should be referenced for documentation-stage questions instead of quotation routing.', 'Public resource center for datasheets, reports, FAQ and supporting references.', array['resources', 'datasheets', 'reports', 'faq', 'case studies', 'whitepapers'], 'site_entry', 'resources', 'Resources', 'Use this for documentation-stage questions.', '/resources/', 'site/resources', 140, 45),
        ('https://www.gasgx.com/support/', 'GasGx Support', 'Public support section for service, tech and network information.', 'GasGx Support is the public support section covering service, technical support and network-facing information. It should be used when the user is asking about service boundaries rather than only product selection.', 'Public support section for service, tech and network information.', array['support', 'service', 'technical support', 'service network'], 'site_entry', 'support', 'Support', 'Open this when the request is mainly support-oriented.', '/support/', 'site/support', 150, 40),
        ('https://www.gasgx.com/rankings/', 'GasGx Rankings', 'Public comparative and ranking-style pages.', 'GasGx Rankings is the public comparative section for ranking-style pages, benchmarking views and market-facing comparisons. It should be used when the user wants comparison-oriented content rather than a direct quotation path.', 'Public comparative and ranking-style pages.', array['rankings', 'comparison', 'benchmark', 'ranking pages'], 'site_entry', 'rankings', 'Rankings', 'Use this for comparison-oriented public pages.', '/rankings/', 'site/rankings', 160, 37),
        ('https://www.gasgx.com/tools/', 'GasGx Tools', 'Public tool hub for screening, calculators, analyzers and comparisons.', 'GasGx Tools is the public tool hub for screening, calculators, analyzers and scenario-comparison utilities. It is the right feature entry when the user asks which public tool to use first or which calculators are available.', 'Public tool hub for screening, calculators, analyzers and comparisons.', array['tools', 'tool hub', 'calculator', 'analyzer', 'screening tool'], 'site_entry', 'tools', 'GasGx Tools', 'Use this when the request is about public tools.', '/tools/', 'site/tools', 170, 44),
        ('https://www.gasgx.com/digitalization/platform/', 'GasGx O&M Platform', 'Public digitalization entry for the O&M platform capability page.', 'The GasGx O&M Platform page acts as the main public digitalization entry for operations visibility, diagnostics and platform capability positioning. It is suitable for public digital-system questions, but not for opening internal admin consoles.', 'Public digitalization entry for the O&M platform capability page.', array['digitalization', 'o&m platform', 'operations platform', 'monitoring'], 'digitalization', 'o_m_platform', 'O&M Platform', 'Use this for public digitalization capability questions.', '/digitalization/platform/', 'digitalization/platform', 180, 43),
        ('https://www.gasgx.com/about/contact/', 'Contact GasGx', 'Public contact entry for project, support and cooperation requests.', 'Contact GasGx is the public contact page for project, support and cooperation requests. It is the right route when the visitor needs a public contact entry rather than an internal operator or admin path.', 'Public contact entry for project, support and cooperation requests.', array['contact', 'contact gasgx', 'email', 'support contact'], 'support', 'contact', 'Contact GasGx', 'Use this when the user needs a public contact path.', '/about/contact/', 'support/contact', 190, 40),
        ('https://www.gasgx.com/quote/requirement.html', 'GasGx Requirement Intake', 'Public structured intake for quotation and project qualification.', 'GasGx Requirement Intake is the public structured intake page for quotation follow-up and project qualification. It captures application, power, gas type, gas quality, country, deployment preference and scope boundary in one place.', 'Public structured intake for quotation and project qualification.', array['requirement intake', 'quote form', 'quotation form', 'project brief', 'requirement form'], 'workflow', 'requirement_intake', 'GasGx Requirement Intake', 'Use this when the user needs the public quotation workflow.', '/quote/requirement.html', 'workflow/requirement-intake', 200, 48),
        ('https://www.gasgx.com/solutions/oilfield/', 'Oilfield Solution', 'Public oilfield gas-to-power solution page.', 'The Oilfield Solution page is the public scenario page for oilfield and associated-gas power positioning. It is the correct public route when the user asks for the oilfield solution page instead of a generic scenario summary.', 'Public oilfield gas-to-power solution page.', array['oilfield solution', 'oilfield page', 'associated gas power'], 'solution', 'oilfield_solution', 'Oilfield Solution', 'Use this when the visitor asks for the oilfield scenario page.', '/solutions/oilfield/', 'solutions/oilfield', 210, 38),
        ('https://www.gasgx.com/solutions/mining/', 'Mining Solution', 'Public mining and data-center power solution page.', 'The Mining Solution page is the public scenario page for gas-to-power mining and data-center-style power positioning. It should be referenced when the user asks for the mining solution page rather than a quotation or tool answer.', 'Public mining and data-center power solution page.', array['mining solution', 'data center power', 'mining page'], 'solution', 'mining_solution', 'Mining Solution', 'Use this when the visitor asks for the mining scenario page.', '/solutions/mining/', 'solutions/mining', 220, 39),
        ('https://www.gasgx.com/solutions/industrial/', 'Industrial Solution', 'Public industrial distributed-generation solution page.', 'The Industrial Solution page is the public scenario page for industrial distributed generation and plant-side power positioning. It is the right route when the question is about industrial scenario navigation.', 'Public industrial distributed-generation solution page.', array['industrial solution', 'industrial page', 'distributed generation'], 'solution', 'industrial_solution', 'Industrial Solution', 'Use this when the visitor asks for the industrial scenario page.', '/solutions/industrial/', 'solutions/industrial', 230, 38),
        ('https://www.gasgx.com/solutions/chp/', 'CHP Solution', 'Public CHP and cogeneration solution page.', 'The CHP Solution page is the public route for CHP and cogeneration positioning. It should be referenced when the visitor explicitly asks for the CHP page or wants the public CHP entry.', 'Public CHP and cogeneration solution page.', array['chp solution', 'cogeneration', 'chp page'], 'solution', 'chp_solution', 'CHP Solution', 'Use this when the visitor asks for the CHP scenario page.', '/solutions/chp/', 'solutions/chp', 240, 35),
        ('https://www.gasgx.com/resources/datasheets/', 'GasGx Datasheets', 'Public datasheet library for equipment-detail references.', 'GasGx Datasheets is the public resource entry for equipment-detail references and parameter-sheet style documents. It is the best public route when the question is specifically about datasheets.', 'Public datasheet library for equipment-detail references.', array['datasheets', 'data sheets', 'parameter sheets', 'equipment details'], 'resource', 'datasheets', 'Datasheets', 'Use this when the visitor asks for datasheets.', '/resources/datasheets/', 'resources/datasheets', 250, 39),
        ('https://www.gasgx.com/resources/reports/', 'GasGx Reports', 'Public reports library for market and scenario context.', 'GasGx Reports is the public resource entry for market context, scenario research and longer-form report reading. It is the right route when the question is about reports rather than short FAQ answers.', 'Public reports library for market and scenario context.', array['reports', 'market reports', 'research reports'], 'resource', 'reports', 'Reports', 'Use this when the visitor asks for reports.', '/resources/reports/', 'resources/reports', 260, 36),
        ('https://www.gasgx.com/resources/faq/', 'GasGx FAQ', 'Public FAQ entry for short operational answers.', 'GasGx FAQ is the public short-answer entry for operational and repeated questions. It should be referenced when the visitor wants a fast FAQ-style answer before opening longer documents.', 'Public FAQ entry for short operational answers.', array['faq', 'frequently asked questions', 'short answers'], 'resource', 'faq', 'FAQ', 'Use this when the visitor asks for FAQ.', '/resources/faq/', 'resources/faq', 270, 33),
        ('https://www.gasgx.com/resources/case-studies/', 'GasGx Case Studies', 'Public case-studies library with reference scenarios.', 'GasGx Case Studies is the public case library for reference scenarios and example-style reading. It is useful when the visitor wants examples rather than only specifications.', 'Public case-studies library with reference scenarios.', array['case studies', 'case study', 'reference scenarios'], 'resource', 'case_studies', 'Case Studies', 'Use this when the visitor asks for public examples.', '/resources/case-studies/', 'resources/case-studies', 280, 34),
        ('https://www.gasgx.com/resources/videos/', 'GasGx Videos', 'Public videos library for visual references.', 'GasGx Videos is the public visual reference entry for visitors who prefer video-based overview instead of document-first reading. It is suitable for visual and media-driven guidance.', 'Public videos library for visual references.', array['videos', 'video library', 'visual overview'], 'resource', 'videos', 'Videos', 'Use this when the visitor asks for video references.', '/resources/videos/', 'resources/videos', 290, 31),
        ('https://www.gasgx.com/resources/certifications/', 'GasGx Certifications', 'Public certifications page for certification references.', 'GasGx Certifications is the public certification-reference page. It is useful for certification references, but it should not be treated as a project-specific compliance approval by itself.', 'Public certifications page for certification references.', array['certifications', 'certification page', 'certificate references'], 'resource', 'certifications', 'Certifications', 'Use this when the visitor asks for certification references.', '/resources/certifications/', 'resources/certifications', 300, 35),
        ('https://www.gasgx.com/resources/whitepapers/', 'GasGx Whitepapers', 'Public whitepapers library for longer-form reading.', 'GasGx Whitepapers is the public long-form reading entry for deeper technical or market background. It is useful when the visitor wants a public whitepaper route.', 'Public whitepapers library for longer-form reading.', array['whitepapers', 'white paper', 'long-form resource'], 'resource', 'whitepapers', 'Whitepapers', 'Use this when the visitor asks for whitepapers.', '/resources/whitepapers/', 'resources/whitepapers', 310, 32),
        ('https://www.gasgx.com/support/service/', 'GasGx Service Support', 'Public service-support page.', 'GasGx Service Support is the public service-oriented support page for after-sales and service-boundary questions. It should be used when the visitor wants service-scope direction rather than only a product page.', 'Public service-support page.', array['service support', 'after-sales service', 'service page'], 'support', 'service_support', 'Service Support', 'Use this when the visitor asks about service support.', '/support/service/', 'support/service', 320, 34),
        ('https://www.gasgx.com/support/network/', 'GasGx Service Network', 'Public service-network page.', 'GasGx Service Network is the public entry for regional support-reach and network-facing service questions. It should be used when the visitor asks about network coverage or support reach.', 'Public service-network page.', array['service network', 'support network', 'regional support'], 'support', 'service_network', 'Service Network', 'Use this when the visitor asks about service-network reach.', '/support/network/', 'support/network', 330, 33),
        ('https://www.gasgx.com/support/tech/', 'GasGx Technical Support', 'Public technical-support page.', 'GasGx Technical Support is the public entry for technical-support scope questions. It is the right route when the visitor asks where technical support information lives on the public site.', 'Public technical-support page.', array['technical support', 'tech support', 'support tech'], 'support', 'technical_support', 'Technical Support', 'Use this when the visitor asks about technical support.', '/support/tech/', 'support/tech', 340, 32),
        ('https://www.gasgx.com/vman/', 'VMAN', 'Public VMAN brand entry.', 'VMAN is a public GasGx brand-facing route that can act as a public quote or brand entry. It should be referenced when the visitor explicitly asks for the VMAN page.', 'Public VMAN brand entry.', array['vman', 'vman page', 'brand entry'], 'brand', 'vman', 'VMAN', 'Use this when the visitor asks for the public VMAN route.', '/vman/', 'brand/vman', 350, 30),
        ('https://www.gasgx.com/minerpower/', 'MinerPower', 'Public MinerPower brand entry.', 'MinerPower is a public GasGx brand-facing route for the MinerPower page. It should be referenced when the visitor explicitly asks for the public MinerPower route.', 'Public MinerPower brand entry.', array['minerpower', 'miner power', 'minerpower page'], 'brand', 'minerpower', 'MinerPower', 'Use this when the visitor asks for the public MinerPower route.', '/minerpower/', 'brand/minerpower', 360, 30),
        ('https://www.gasgx.com/tools/site-fit/', 'Site Fit Tool', 'Public feasibility-screening tool for overall project fit.', 'The Site Fit Tool is the first public screening tool for overall project feasibility before quotation. It is the best public route when the visitor asks which tool to use first for feasibility screening.', 'Public feasibility-screening tool for overall project fit.', array['site fit', 'site-fit', 'feasibility screening', 'project fit'], 'tool', 'site_fit', 'Site Fit Tool', 'Use this as the first public screening tool.', '/tools/site-fit/', 'tools/site-fit', 370, 39),
        ('https://www.gasgx.com/tools/gas-fit/', 'Gas Fit Tool', 'Public tool for checking fuel and gas-boundary fit.', 'The Gas Fit Tool is the public route for checking whether the gas source and fuel boundary look workable for a GasGx solution. It should be referenced when the visitor asks about gas-fit screening.', 'Public tool for checking fuel and gas-boundary fit.', array['gas fit', 'gas-fit', 'fuel fit', 'gas boundary'], 'tool', 'gas_fit', 'Gas Fit Tool', 'Use this for fuel-boundary screening.', '/tools/gas-fit/', 'tools/gas-fit', 380, 38),
        ('https://www.gasgx.com/tools/engine-selection/', 'Engine Selection Tool', 'Public tool for narrowing equipment direction.', 'The Engine Selection Tool is the public route for narrowing equipment direction before formal quotation. It should be used when the visitor asks about generator or engine direction as a public tool.', 'Public tool for narrowing equipment direction.', array['engine selection', 'engine-selection', 'generator selection'], 'tool', 'engine_selection', 'Engine Selection Tool', 'Use this to narrow equipment direction before quotation.', '/tools/engine-selection/', 'tools/engine-selection', 390, 38),
        ('https://www.gasgx.com/tools/miner-buying-guide/', 'Miner Buying Guide', 'Public tool for miner procurement direction.', 'Miner Buying Guide is the public route for comparing miner procurement direction against the planned power strategy. It is useful when the visitor asks for a miner-buying guide rather than a quotation workflow.', 'Public tool for miner procurement direction.', array['miner buying guide', 'buying guide', 'miner guide'], 'tool', 'miner_buying_guide', 'Miner Buying Guide', 'Use this when the request is miner-procurement oriented.', '/tools/miner-buying-guide/', 'tools/miner-buying-guide', 400, 34),
        ('https://www.gasgx.com/tools/roi/', 'ROI Calculator', 'Public ROI calculator entry.', 'The ROI Calculator is the public route for estimating return-on-investment direction. It is useful for directional analysis, but should not be treated as a final project commitment.', 'Public ROI calculator entry.', array['roi', 'roi calculator', 'return on investment'], 'tool', 'roi_calculator', 'ROI Calculator', 'Use this for directional ROI analysis.', '/tools/roi/', 'tools/roi', 410, 33),
        ('https://www.gasgx.com/tools/lcoe-calculator/', 'LCOE Calculator', 'Public LCOE calculator entry.', 'The LCOE Calculator is the public route for estimating levelized electricity-cost direction. It is useful when the visitor asks for cost-direction analysis rather than final quotation.', 'Public LCOE calculator entry.', array['lcoe', 'lcoe calculator', 'levelized cost of electricity'], 'tool', 'lcoe_calculator', 'LCOE Calculator', 'Use this for directional electricity-cost analysis.', '/tools/lcoe-calculator/', 'tools/lcoe-calculator', 420, 35),
        ('https://www.gasgx.com/tools/gas-analyzer/', 'Gas Analyzer', 'Public gas-analysis tool entry.', 'Gas Analyzer is the public route for gas-composition and gas-analysis style questions. It is useful when the visitor asks for a gas analyzer rather than a broader quotation route.', 'Public gas-analysis tool entry.', array['gas analyzer', 'gas analyser', 'gas analysis'], 'tool', 'gas_analyzer', 'Gas Analyzer', 'Use this for gas-analysis questions.', '/tools/gas-analyzer/', 'tools/gas-analyzer', 430, 31),
        ('https://www.gasgx.com/tools/global-logistics/', 'Global Logistics', 'Public logistics-analysis tool entry.', 'Global Logistics is the public route for transport, routing and delivery-boundary analysis. It should be referenced when the visitor asks about logistics constraints as a public site feature.', 'Public logistics-analysis tool entry.', array['global logistics', 'logistics', 'shipping constraints'], 'tool', 'global_logistics', 'Global Logistics', 'Use this for logistics-boundary analysis.', '/tools/global-logistics/', 'tools/global-logistics', 440, 33),
        ('https://www.gasgx.com/tools/global-compliance/', 'Global Compliance', 'Public compliance-analysis tool entry.', 'Global Compliance is the public route for high-level compliance and market-entry analysis. It should be referenced when the visitor asks whether GasGx has a public compliance-oriented tool.', 'Public compliance-analysis tool entry.', array['global compliance', 'compliance', 'regulatory'], 'tool', 'global_compliance', 'Global Compliance', 'Use this for high-level compliance analysis.', '/tools/global-compliance/', 'tools/global-compliance', 450, 33)
)
insert into public.knowledge_chunks (
    document_id,
    chunk_text,
    chunk_summary,
    language,
    keywords,
    section_path,
    sort_order,
    token_count,
    source_meta,
    search_text
)
select
    kd.id,
    seed.chunk_text,
    seed.chunk_summary,
    'en',
    seed.keywords,
    seed.section_path,
    seed.sort_order,
    seed.token_count,
    jsonb_build_object(
        'seed', 'public_site_feature_directory_v1',
        'kind', 'site_function',
        'feature_group', seed.feature_group,
        'feature_id', seed.feature_id,
        'path', seed.path,
        'link_label', seed.link_label,
        'recommendation_hint', seed.recommendation_hint
    ),
    seed.chunk_text || ' ' || seed.chunk_summary || ' ' || array_to_string(seed.keywords, ' ')
from seed
join public.knowledge_documents kd
    on kd.canonical_url = seed.canonical_url
where kd.status = 'published';
