create table if not exists public.site_shell_configs (
    id bigint generated by default as identity primary key,
    scope text not null,
    config jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default timezone('utc', now()),
    updated_by text
);

create unique index if not exists site_shell_configs_scope_idx
    on public.site_shell_configs (scope);

alter table public.site_shell_configs enable row level security;

drop policy if exists "public read global site shell configs" on public.site_shell_configs;
create policy "public read global site shell configs"
    on public.site_shell_configs
    for select
    to anon, authenticated
    using (scope = 'global');

drop policy if exists "admins manage site shell configs" on public.site_shell_configs;
create policy "admins manage site shell configs"
    on public.site_shell_configs
    for all
    to authenticated
    using (lower(coalesce(auth.jwt() ->> 'email', '')) in ('cuitengwei@gasgx.com'))
    with check (lower(coalesce(auth.jwt() ->> 'email', '')) in ('cuitengwei@gasgx.com'));

insert into public.site_shell_configs (scope, config)
values ('global', '{}'::jsonb)
on conflict (scope) do nothing;
